version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    open-pull-requests-limit: 10
    versioning-strategy: increase
