{{ note_comment }}

FROM {{ php_image }}

ARG BUILD_DATE
ARG VCS_REF
{% if use_xdebug %}
ARG XDEBUG_VERSION
{% endif %}

LABEL org.opencontainers.image.title="juliangut/phpdev" \
  org.opencontainers.image.description="PHP/PHP-FPM/Jenkins Docker image for development/CI, based on Alpine Linux for minimal size" \
  org.opencontainers.image.url="https://github.com/juliangut/docker-phpdev" \
  org.opencontainers.image.source="https://github.com/juliangut/docker-phpdev/tree/master/dist/{{ source_path }}" \
  org.opencontainers.image.revision="$VCS_REF" \
  org.opencontainers.image.created="$BUILD_DATE" \
  org.opencontainers.image.authors="Julián Gutiérrez (juliangut@gmail.com)" \
  org.opencontainers.image.licenses="BSD-3-Clause" \
  com.juliangut.php.version="{{ php_version }}" \
  com.juliangut.php.extensions="bcmath, curl, gd, mbstring, opcache, openssl, {% if use_xdebug %}xdebug, {% endif %}zlib"{% if use_xdebug %} \
  com.juliangut.xdebug.version="$XDEBUG_VERSION"{% endif %}


RUN set -xe \
  && apk add --no-cache --virtual .build-deps \
    tzdata \
    $PHPIZE_DEPS \
  \
  && cp /usr/share/zoneinfo/UTC /etc/localtime \
  && echo "UTC" > /etc/timezone \
  \
  && apk add --no-cache \
    shadow \
    sudo \
    bash \
    freetype-dev \
    libpng-dev \
    libjpeg-turbo-dev \
    libwebp-dev \
{% block install %}{% endblock %}
  \
  && groupmod -n docker www-data \
  && usermod -l docker -m -d /home/docker -s /sbin/bash -G wheel -a www-data \
  && sed -e 's;^# \(%wheel.*NOPASSWD.*\);\1;g' -i /etc/sudoers \
  \
{% block user %}{% endblock %}
  && docker-php-ext-configure \
    gd \
{% if php_version < 7.4 %}
      --with-freetype-dir \
      --with-png-dir \
      --with-jpeg-dir \
      --with-webp-dir \
{% else %}
      --with-freetype \
      --with-jpeg \
      --with-webp \
{% endif %}
  \
  && docker-php-ext-install \
    gd \
    bcmath \
    opcache \
  \
{% if use_xdebug %}
  && pecl update-channels \
  && pecl install \
    xdebug-$XDEBUG_VERSION \
  \
  && docker-php-ext-enable \
    xdebug \
  \
{% endif %}
  && apk del .build-deps \
  && rm -rf /tmp/* /var/cache/apk/* \
  \
  && sed -i "s/bin\/ash/bin\/bash/" /etc/passwd \
  \
  && php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');" \
    && php -r "copy('https://composer.github.io/installer.sig', '/tmp/composer-setup.sig');"  \
    && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { echo 'Invalid Composer installer' . PHP_EOL; exit(1); }" \
    && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm -f /tmp/composer-setup.php \
    && rm -f /tmp/composer-setup.sig \
    && composer global require hirak/prestissimo \
    && composer global clear-cache \
  \
  && mv /root/.composer /home/docker/.composer \
  && chown docker:docker -R /home/docker/.composer \
  \
  && mkdir /app \
  && chown docker:docker /app \
  \
  && mkdir -p /var/log/php \
{% if use_xdebug %}
  && touch /var/log/php/xdebug.log \
{% endif %}
  && chown docker:docker -R /var/log/php \
  && chmod 774 -R /var/log/php

ENV STDOUT_LOG=0 \
  \
  XDEBUG_DISABLE=0 \
  XDEBUG_REMOTE_AUTOSTART=0 \
  XDEBUG_REMOTE_PORT=9000 \
  XDEBUG_PROFILER_ENABLE=0 \
  XDEBUG_AUTO_TRACE=0 \
  \
  OPCACHE_VALIDATE_TIMESTAMP=1 \
  OPCACHE_MEMORY_CONSUMPTION=128 \
  OPCACHE_MAX_ACCELERATED_FILES=1000 \
  \
  COMPOSER_ALLOW_SUPERUSER=1 \
{% if use_xdebug %}
  COMPOSER_DISABLE_XDEBUG_WARN=1 \
{% endif %}
  \
  PATH="/home/docker/.composer/vendor/bin:$PATH"

COPY php.ini $PHP_INI_DIR/conf.d/zz-php.ini
COPY opcache.ini $PHP_INI_DIR/conf.d/zz-opcache.ini
{% if use_xdebug %}
COPY xdebug.ini $PHP_INI_DIR/conf.d/zz-xdebug.ini
{% endif %}
{% block files %}{% endblock %}

VOLUME /app /var/log/php
WORKDIR /app

COPY docker-entrypoint /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint
ENTRYPOINT ["docker-entrypoint"]

{% block command %}{% endblock %}

{{ note_comment }}
