{% extends "Dockerfile.twig" %}

{% block files %}

ENV PHP_FPM_CONF_DIR /usr/local/etc/php-fpm.d
COPY php-fpm.conf $PHP_FPM_CONF_DIR/zz-php-fpm.conf
{% endblock %}

{% block command %}
CMD ["php-fpm"]
{% endblock %}
