{% extends "Dockerfile.twig" %}

{% block install %}
    openjdk8-jre \
    openssh \
    git \
{% endblock %}

{% block user %}
  && addgroup -g 1551 jenkins \
  && adduser -u 1551 -G jenkins -h /home/jenkins -s /sbin/bash -D jenkins \
  && echo "jenkins:jenkins" | chpasswd \
  \
{% endblock %}

{% block command %}
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
{% endblock %}
